/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AddAccountRouteImport } from './routes/add-account'
import { Route as AddAdminRouteImport } from './routes/add-admin'
import { Route as AddBusinessRouteImport } from './routes/add-business'
import { Route as AddCashEntryRouteImport } from './routes/add-cash-entry'
import { Route as AddTransactionRouteImport } from './routes/add-transaction'
import { Route as BalanceSheetRouteImport } from './routes/balance-sheet'
import { Route as BranchRouteImport } from './routes/branch'
import { Route as BranchEditRouteImport } from './routes/branch-edit'
import { Route as BranchViewRouteImport } from './routes/branch-view'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CashBookRouteImport } from './routes/cash-book'
import { Route as CreateBranchRouteImport } from './routes/create-branch'
import { Route as CreateUserRouteImport } from './routes/create-user'
import { Route as CustomerFileRouteImport } from './routes/customer-file'
import { Route as CustomerPortalRouteImport } from './routes/customer-portal'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DebtorPaymentRouteImport } from './routes/debtor-payment'
import { Route as EditAdminRouteImport } from './routes/edit-admin'
import { Route as EditBusinessRouteImport } from './routes/edit-business'
import { Route as EditProductRouteImport } from './routes/edit-product'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ExpiryRouteImport } from './routes/expiry'
import { Route as IncomeStatementRouteImport } from './routes/income-statement'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicePreviewRouteImport } from './routes/invoice-preview'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ListBranchesRouteImport } from './routes/list-branches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageAdminRouteImport } from './routes/manage-admin'
import { Route as ManageBusinessRouteImport } from './routes/manage-business'
import { Route as ManagerDashboardRouteImport } from './routes/manager-dashboard'
import { Route as NotificationRouteImport } from './routes/notification'
import { Route as OrderNotificationsRouteImport } from './routes/order-notifications'
import { Route as PaymentProofsRouteImport } from './routes/payment-proofs'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PayrollPayslipRouteImport } from './routes/payroll-payslip'
import { Route as PayslipRouteImport } from './routes/payslip'
import { Route as PettyCashRouteImport } from './routes/petty-cash'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProductImagesRouteImport } from './routes/product-images'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QrScannerRouteImport } from './routes/qr-scanner'
import { Route as ReceiptPreviewRouteImport } from './routes/receipt-preview'
import { Route as RemoteOrdersRouteImport } from './routes/remote-orders'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportsGeneratorRouteImport } from './routes/reports-generator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as StaffDashboardRouteImport } from './routes/staff-dashboard'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SuperRouteImport } from './routes/super'
import { Route as SuperReportRouteImport } from './routes/super-report'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SystemUpdatesRouteImport } from './routes/system-updates'
import { Route as TillManagementRouteImport } from './routes/till-management'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TrailBalanceRouteImport } from './routes/trail-balance'
import { Route as ViewBusinessRouteImport } from './routes/view-business'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AddAccountRoute = AddAccountRouteImport.update({
  id: '/add-account',
  path: '/add-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AddAdminRoute = AddAdminRouteImport.update({
  id: '/add-admin',
  path: '/add-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBusinessRoute = AddBusinessRouteImport.update({
  id: '/add-business',
  path: '/add-business',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCashEntryRoute = AddCashEntryRouteImport.update({
  id: '/add-cash-entry',
  path: '/add-cash-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTransactionRoute = AddTransactionRouteImport.update({
  id: '/add-transaction',
  path: '/add-transaction',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceSheetRoute = BalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchRoute = BranchRouteImport.update({
  id: '/branch',
  path: '/branch',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchEditRoute = BranchEditRouteImport.update({
  id: '/branch-edit',
  path: '/branch-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchViewRoute = BranchViewRouteImport.update({
  id: '/branch-view',
  path: '/branch-view',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBookRoute = CashBookRouteImport.update({
  id: '/cash-book',
  path: '/cash-book',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBranchRoute = CreateBranchRouteImport.update({
  id: '/create-branch',
  path: '/create-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateUserRoute = CreateUserRouteImport.update({
  id: '/create-user',
  path: '/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerFileRoute = CustomerFileRouteImport.update({
  id: '/customer-file',
  path: '/customer-file',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer-portal',
  path: '/customer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtorPaymentRoute = DebtorPaymentRouteImport.update({
  id: '/debtor-payment',
  path: '/debtor-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const EditAdminRoute = EditAdminRouteImport.update({
  id: '/edit-admin',
  path: '/edit-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EditBusinessRoute = EditBusinessRouteImport.update({
  id: '/edit-business',
  path: '/edit-business',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProductRoute = EditProductRouteImport.update({
  id: '/edit-product',
  path: '/edit-product',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiryRoute = ExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeStatementRoute = IncomeStatementRouteImport.update({
  id: '/income-statement',
  path: '/income-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicePreviewRoute = InvoicePreviewRouteImport.update({
  id: '/invoice-preview',
  path: '/invoice-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ListBranchesRoute = ListBranchesRouteImport.update({
  id: '/list-branches',
  path: '/list-branches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAdminRoute = ManageAdminRouteImport.update({
  id: '/manage-admin',
  path: '/manage-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBusinessRoute = ManageBusinessRouteImport.update({
  id: '/manage-business',
  path: '/manage-business',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager-dashboard',
  path: '/manager-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationRoute = NotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderNotificationsRoute = OrderNotificationsRouteImport.update({
  id: '/order-notifications',
  path: '/order-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentProofsRoute = PaymentProofsRouteImport.update({
  id: '/payment-proofs',
  path: '/payment-proofs',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollPayslipRoute = PayrollPayslipRouteImport.update({
  id: '/payroll-payslip',
  path: '/payroll-payslip',
  getParentRoute: () => rootRouteImport,
} as any)
const PayslipRoute = PayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => rootRouteImport,
} as any)
const PettyCashRoute = PettyCashRouteImport.update({
  id: '/petty-cash',
  path: '/petty-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductImagesRoute = ProductImagesRouteImport.update({
  id: '/product-images',
  path: '/product-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QrScannerRoute = QrScannerRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPreviewRoute = ReceiptPreviewRouteImport.update({
  id: '/receipt-preview',
  path: '/receipt-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteOrdersRoute = RemoteOrdersRouteImport.update({
  id: '/remote-orders',
  path: '/remote-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsGeneratorRoute = ReportsGeneratorRouteImport.update({
  id: '/reports-generator',
  path: '/reports-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff-dashboard',
  path: '/staff-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperReportRoute = SuperReportRouteImport.update({
  id: '/super-report',
  path: '/super-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUpdatesRoute = SystemUpdatesRouteImport.update({
  id: '/system-updates',
  path: '/system-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TillManagementRoute = TillManagementRouteImport.update({
  id: '/till-management',
  path: '/till-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailBalanceRoute = TrailBalanceRouteImport.update({
  id: '/trail-balance',
  path: '/trail-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewBusinessRoute = ViewBusinessRouteImport.update({
  id: '/view-business',
  path: '/view-business',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/add-account': typeof AddAccountRoute
  '/add-admin': typeof AddAdminRoute
  '/add-business': typeof AddBusinessRoute
  '/add-cash-entry': typeof AddCashEntryRoute
  '/add-transaction': typeof AddTransactionRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/branch': typeof BranchRoute
  '/branch-edit': typeof BranchEditRoute
  '/branch-view': typeof BranchViewRoute
  '/branches': typeof BranchesRoute
  '/cash-book': typeof CashBookRoute
  '/create-branch': typeof CreateBranchRoute
  '/create-user': typeof CreateUserRoute
  '/customer-file': typeof CustomerFileRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/customers': typeof CustomersRoute
  '/debtor-payment': typeof DebtorPaymentRoute
  '/edit-admin': typeof EditAdminRoute
  '/edit-business': typeof EditBusinessRoute
  '/edit-product': typeof EditProductRoute
  '/employee': typeof EmployeeRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/expiry': typeof ExpiryRoute
  '/income-statement': typeof IncomeStatementRoute
  '/inventory': typeof InventoryRoute
  '/invoice-preview': typeof InvoicePreviewRoute
  '/ledger': typeof LedgerRoute
  '/list-branches': typeof ListBranchesRoute
  '/login': typeof LoginRoute
  '/manage-admin': typeof ManageAdminRoute
  '/manage-business': typeof ManageBusinessRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/notification': typeof NotificationRoute
  '/order-notifications': typeof OrderNotificationsRoute
  '/payment-proofs': typeof PaymentProofsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-payslip': typeof PayrollPayslipRoute
  '/payslip': typeof PayslipRoute
  '/petty-cash': typeof PettyCashRoute
  '/pos': typeof PosRoute
  '/product-images': typeof ProductImagesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/qr-scanner': typeof QrScannerRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/remote-orders': typeof RemoteOrdersRoute
  '/reports': typeof ReportsRoute
  '/reports-generator': typeof ReportsGeneratorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/sms': typeof SmsRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/subscription': typeof SubscriptionRoute
  '/super': typeof SuperRoute
  '/super-report': typeof SuperReportRoute
  '/suppliers': typeof SuppliersRoute
  '/system-updates': typeof SystemUpdatesRoute
  '/till-management': typeof TillManagementRoute
  '/track-order': typeof TrackOrderRoute
  '/trail-balance': typeof TrailBalanceRoute
  '/view-business': typeof ViewBusinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/add-account': typeof AddAccountRoute
  '/add-admin': typeof AddAdminRoute
  '/add-business': typeof AddBusinessRoute
  '/add-cash-entry': typeof AddCashEntryRoute
  '/add-transaction': typeof AddTransactionRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/branch': typeof BranchRoute
  '/branch-edit': typeof BranchEditRoute
  '/branch-view': typeof BranchViewRoute
  '/branches': typeof BranchesRoute
  '/cash-book': typeof CashBookRoute
  '/create-branch': typeof CreateBranchRoute
  '/create-user': typeof CreateUserRoute
  '/customer-file': typeof CustomerFileRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/customers': typeof CustomersRoute
  '/debtor-payment': typeof DebtorPaymentRoute
  '/edit-admin': typeof EditAdminRoute
  '/edit-business': typeof EditBusinessRoute
  '/edit-product': typeof EditProductRoute
  '/employee': typeof EmployeeRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/expiry': typeof ExpiryRoute
  '/income-statement': typeof IncomeStatementRoute
  '/inventory': typeof InventoryRoute
  '/invoice-preview': typeof InvoicePreviewRoute
  '/ledger': typeof LedgerRoute
  '/list-branches': typeof ListBranchesRoute
  '/login': typeof LoginRoute
  '/manage-admin': typeof ManageAdminRoute
  '/manage-business': typeof ManageBusinessRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/notification': typeof NotificationRoute
  '/order-notifications': typeof OrderNotificationsRoute
  '/payment-proofs': typeof PaymentProofsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-payslip': typeof PayrollPayslipRoute
  '/payslip': typeof PayslipRoute
  '/petty-cash': typeof PettyCashRoute
  '/pos': typeof PosRoute
  '/product-images': typeof ProductImagesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/qr-scanner': typeof QrScannerRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/remote-orders': typeof RemoteOrdersRoute
  '/reports': typeof ReportsRoute
  '/reports-generator': typeof ReportsGeneratorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/sms': typeof SmsRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/subscription': typeof SubscriptionRoute
  '/super': typeof SuperRoute
  '/super-report': typeof SuperReportRoute
  '/suppliers': typeof SuppliersRoute
  '/system-updates': typeof SystemUpdatesRoute
  '/till-management': typeof TillManagementRoute
  '/track-order': typeof TrackOrderRoute
  '/trail-balance': typeof TrailBalanceRoute
  '/view-business': typeof ViewBusinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/add-account': typeof AddAccountRoute
  '/add-admin': typeof AddAdminRoute
  '/add-business': typeof AddBusinessRoute
  '/add-cash-entry': typeof AddCashEntryRoute
  '/add-transaction': typeof AddTransactionRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/branch': typeof BranchRoute
  '/branch-edit': typeof BranchEditRoute
  '/branch-view': typeof BranchViewRoute
  '/branches': typeof BranchesRoute
  '/cash-book': typeof CashBookRoute
  '/create-branch': typeof CreateBranchRoute
  '/create-user': typeof CreateUserRoute
  '/customer-file': typeof CustomerFileRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/customers': typeof CustomersRoute
  '/debtor-payment': typeof DebtorPaymentRoute
  '/edit-admin': typeof EditAdminRoute
  '/edit-business': typeof EditBusinessRoute
  '/edit-product': typeof EditProductRoute
  '/employee': typeof EmployeeRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/expiry': typeof ExpiryRoute
  '/income-statement': typeof IncomeStatementRoute
  '/inventory': typeof InventoryRoute
  '/invoice-preview': typeof InvoicePreviewRoute
  '/ledger': typeof LedgerRoute
  '/list-branches': typeof ListBranchesRoute
  '/login': typeof LoginRoute
  '/manage-admin': typeof ManageAdminRoute
  '/manage-business': typeof ManageBusinessRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/notification': typeof NotificationRoute
  '/order-notifications': typeof OrderNotificationsRoute
  '/payment-proofs': typeof PaymentProofsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-payslip': typeof PayrollPayslipRoute
  '/payslip': typeof PayslipRoute
  '/petty-cash': typeof PettyCashRoute
  '/pos': typeof PosRoute
  '/product-images': typeof ProductImagesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/qr-scanner': typeof QrScannerRoute
  '/receipt-preview': typeof ReceiptPreviewRoute
  '/remote-orders': typeof RemoteOrdersRoute
  '/reports': typeof ReportsRoute
  '/reports-generator': typeof ReportsGeneratorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sales': typeof SalesRoute
  '/signup': typeof SignupRoute
  '/sms': typeof SmsRoute
  '/staff-dashboard': typeof StaffDashboardRoute
  '/subscription': typeof SubscriptionRoute
  '/super': typeof SuperRoute
  '/super-report': typeof SuperReportRoute
  '/suppliers': typeof SuppliersRoute
  '/system-updates': typeof SystemUpdatesRoute
  '/till-management': typeof TillManagementRoute
  '/track-order': typeof TrackOrderRoute
  '/trail-balance': typeof TrailBalanceRoute
  '/view-business': typeof ViewBusinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/add-account'
    | '/add-admin'
    | '/add-business'
    | '/add-cash-entry'
    | '/add-transaction'
    | '/balance-sheet'
    | '/branch'
    | '/branch-edit'
    | '/branch-view'
    | '/branches'
    | '/cash-book'
    | '/create-branch'
    | '/create-user'
    | '/customer-file'
    | '/customer-portal'
    | '/customers'
    | '/debtor-payment'
    | '/edit-admin'
    | '/edit-business'
    | '/edit-product'
    | '/employee'
    | '/employees'
    | '/expenses'
    | '/expiry'
    | '/income-statement'
    | '/inventory'
    | '/invoice-preview'
    | '/ledger'
    | '/list-branches'
    | '/login'
    | '/manage-admin'
    | '/manage-business'
    | '/manager-dashboard'
    | '/notification'
    | '/order-notifications'
    | '/payment-proofs'
    | '/payroll'
    | '/payroll-payslip'
    | '/payslip'
    | '/petty-cash'
    | '/pos'
    | '/product-images'
    | '/products'
    | '/profile'
    | '/qr-scanner'
    | '/receipt-preview'
    | '/remote-orders'
    | '/reports'
    | '/reports-generator'
    | '/reset-password'
    | '/sales'
    | '/signup'
    | '/sms'
    | '/staff-dashboard'
    | '/subscription'
    | '/super'
    | '/super-report'
    | '/suppliers'
    | '/system-updates'
    | '/till-management'
    | '/track-order'
    | '/trail-balance'
    | '/view-business'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/add-account'
    | '/add-admin'
    | '/add-business'
    | '/add-cash-entry'
    | '/add-transaction'
    | '/balance-sheet'
    | '/branch'
    | '/branch-edit'
    | '/branch-view'
    | '/branches'
    | '/cash-book'
    | '/create-branch'
    | '/create-user'
    | '/customer-file'
    | '/customer-portal'
    | '/customers'
    | '/debtor-payment'
    | '/edit-admin'
    | '/edit-business'
    | '/edit-product'
    | '/employee'
    | '/employees'
    | '/expenses'
    | '/expiry'
    | '/income-statement'
    | '/inventory'
    | '/invoice-preview'
    | '/ledger'
    | '/list-branches'
    | '/login'
    | '/manage-admin'
    | '/manage-business'
    | '/manager-dashboard'
    | '/notification'
    | '/order-notifications'
    | '/payment-proofs'
    | '/payroll'
    | '/payroll-payslip'
    | '/payslip'
    | '/petty-cash'
    | '/pos'
    | '/product-images'
    | '/products'
    | '/profile'
    | '/qr-scanner'
    | '/receipt-preview'
    | '/remote-orders'
    | '/reports'
    | '/reports-generator'
    | '/reset-password'
    | '/sales'
    | '/signup'
    | '/sms'
    | '/staff-dashboard'
    | '/subscription'
    | '/super'
    | '/super-report'
    | '/suppliers'
    | '/system-updates'
    | '/till-management'
    | '/track-order'
    | '/trail-balance'
    | '/view-business'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/add-account'
    | '/add-admin'
    | '/add-business'
    | '/add-cash-entry'
    | '/add-transaction'
    | '/balance-sheet'
    | '/branch'
    | '/branch-edit'
    | '/branch-view'
    | '/branches'
    | '/cash-book'
    | '/create-branch'
    | '/create-user'
    | '/customer-file'
    | '/customer-portal'
    | '/customers'
    | '/debtor-payment'
    | '/edit-admin'
    | '/edit-business'
    | '/edit-product'
    | '/employee'
    | '/employees'
    | '/expenses'
    | '/expiry'
    | '/income-statement'
    | '/inventory'
    | '/invoice-preview'
    | '/ledger'
    | '/list-branches'
    | '/login'
    | '/manage-admin'
    | '/manage-business'
    | '/manager-dashboard'
    | '/notification'
    | '/order-notifications'
    | '/payment-proofs'
    | '/payroll'
    | '/payroll-payslip'
    | '/payslip'
    | '/petty-cash'
    | '/pos'
    | '/product-images'
    | '/products'
    | '/profile'
    | '/qr-scanner'
    | '/receipt-preview'
    | '/remote-orders'
    | '/reports'
    | '/reports-generator'
    | '/reset-password'
    | '/sales'
    | '/signup'
    | '/sms'
    | '/staff-dashboard'
    | '/subscription'
    | '/super'
    | '/super-report'
    | '/suppliers'
    | '/system-updates'
    | '/till-management'
    | '/track-order'
    | '/trail-balance'
    | '/view-business'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AddAccountRoute: typeof AddAccountRoute
  AddAdminRoute: typeof AddAdminRoute
  AddBusinessRoute: typeof AddBusinessRoute
  AddCashEntryRoute: typeof AddCashEntryRoute
  AddTransactionRoute: typeof AddTransactionRoute
  BalanceSheetRoute: typeof BalanceSheetRoute
  BranchRoute: typeof BranchRoute
  BranchEditRoute: typeof BranchEditRoute
  BranchViewRoute: typeof BranchViewRoute
  BranchesRoute: typeof BranchesRoute
  CashBookRoute: typeof CashBookRoute
  CreateBranchRoute: typeof CreateBranchRoute
  CreateUserRoute: typeof CreateUserRoute
  CustomerFileRoute: typeof CustomerFileRoute
  CustomerPortalRoute: typeof CustomerPortalRoute
  CustomersRoute: typeof CustomersRoute
  DebtorPaymentRoute: typeof DebtorPaymentRoute
  EditAdminRoute: typeof EditAdminRoute
  EditBusinessRoute: typeof EditBusinessRoute
  EditProductRoute: typeof EditProductRoute
  EmployeeRoute: typeof EmployeeRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  ExpiryRoute: typeof ExpiryRoute
  IncomeStatementRoute: typeof IncomeStatementRoute
  InventoryRoute: typeof InventoryRoute
  InvoicePreviewRoute: typeof InvoicePreviewRoute
  LedgerRoute: typeof LedgerRoute
  ListBranchesRoute: typeof ListBranchesRoute
  LoginRoute: typeof LoginRoute
  ManageAdminRoute: typeof ManageAdminRoute
  ManageBusinessRoute: typeof ManageBusinessRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  NotificationRoute: typeof NotificationRoute
  OrderNotificationsRoute: typeof OrderNotificationsRoute
  PaymentProofsRoute: typeof PaymentProofsRoute
  PayrollRoute: typeof PayrollRoute
  PayrollPayslipRoute: typeof PayrollPayslipRoute
  PayslipRoute: typeof PayslipRoute
  PettyCashRoute: typeof PettyCashRoute
  PosRoute: typeof PosRoute
  ProductImagesRoute: typeof ProductImagesRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  QrScannerRoute: typeof QrScannerRoute
  ReceiptPreviewRoute: typeof ReceiptPreviewRoute
  RemoteOrdersRoute: typeof RemoteOrdersRoute
  ReportsRoute: typeof ReportsRoute
  ReportsGeneratorRoute: typeof ReportsGeneratorRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalesRoute: typeof SalesRoute
  SignupRoute: typeof SignupRoute
  SmsRoute: typeof SmsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SuperRoute: typeof SuperRoute
  SuperReportRoute: typeof SuperReportRoute
  SuppliersRoute: typeof SuppliersRoute
  SystemUpdatesRoute: typeof SystemUpdatesRoute
  TillManagementRoute: typeof TillManagementRoute
  TrackOrderRoute: typeof TrackOrderRoute
  TrailBalanceRoute: typeof TrailBalanceRoute
  ViewBusinessRoute: typeof ViewBusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-account': {
      id: '/add-account'
      path: '/add-account'
      fullPath: '/add-account'
      preLoaderRoute: typeof AddAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-admin': {
      id: '/add-admin'
      path: '/add-admin'
      fullPath: '/add-admin'
      preLoaderRoute: typeof AddAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-business': {
      id: '/add-business'
      path: '/add-business'
      fullPath: '/add-business'
      preLoaderRoute: typeof AddBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-cash-entry': {
      id: '/add-cash-entry'
      path: '/add-cash-entry'
      fullPath: '/add-cash-entry'
      preLoaderRoute: typeof AddCashEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-transaction': {
      id: '/add-transaction'
      path: '/add-transaction'
      fullPath: '/add-transaction'
      preLoaderRoute: typeof AddTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance-sheet': {
      id: '/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/balance-sheet'
      preLoaderRoute: typeof BalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch': {
      id: '/branch'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof BranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-edit': {
      id: '/branch-edit'
      path: '/branch-edit'
      fullPath: '/branch-edit'
      preLoaderRoute: typeof BranchEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-view': {
      id: '/branch-view'
      path: '/branch-view'
      fullPath: '/branch-view'
      preLoaderRoute: typeof BranchViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-book': {
      id: '/cash-book'
      path: '/cash-book'
      fullPath: '/cash-book'
      preLoaderRoute: typeof CashBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-branch': {
      id: '/create-branch'
      path: '/create-branch'
      fullPath: '/create-branch'
      preLoaderRoute: typeof CreateBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-user': {
      id: '/create-user'
      path: '/create-user'
      fullPath: '/create-user'
      preLoaderRoute: typeof CreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-file': {
      id: '/customer-file'
      path: '/customer-file'
      fullPath: '/customer-file'
      preLoaderRoute: typeof CustomerFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal': {
      id: '/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debtor-payment': {
      id: '/debtor-payment'
      path: '/debtor-payment'
      fullPath: '/debtor-payment'
      preLoaderRoute: typeof DebtorPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-admin': {
      id: '/edit-admin'
      path: '/edit-admin'
      fullPath: '/edit-admin'
      preLoaderRoute: typeof EditAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-business': {
      id: '/edit-business'
      path: '/edit-business'
      fullPath: '/edit-business'
      preLoaderRoute: typeof EditBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-product': {
      id: '/edit-product'
      path: '/edit-product'
      fullPath: '/edit-product'
      preLoaderRoute: typeof EditProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expiry': {
      id: '/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof ExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-statement': {
      id: '/income-statement'
      path: '/income-statement'
      fullPath: '/income-statement'
      preLoaderRoute: typeof IncomeStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-preview': {
      id: '/invoice-preview'
      path: '/invoice-preview'
      fullPath: '/invoice-preview'
      preLoaderRoute: typeof InvoicePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-branches': {
      id: '/list-branches'
      path: '/list-branches'
      fullPath: '/list-branches'
      preLoaderRoute: typeof ListBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-admin': {
      id: '/manage-admin'
      path: '/manage-admin'
      fullPath: '/manage-admin'
      preLoaderRoute: typeof ManageAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-business': {
      id: '/manage-business'
      path: '/manage-business'
      fullPath: '/manage-business'
      preLoaderRoute: typeof ManageBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-dashboard': {
      id: '/manager-dashboard'
      path: '/manager-dashboard'
      fullPath: '/manager-dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification': {
      id: '/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof NotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-notifications': {
      id: '/order-notifications'
      path: '/order-notifications'
      fullPath: '/order-notifications'
      preLoaderRoute: typeof OrderNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-proofs': {
      id: '/payment-proofs'
      path: '/payment-proofs'
      fullPath: '/payment-proofs'
      preLoaderRoute: typeof PaymentProofsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-payslip': {
      id: '/payroll-payslip'
      path: '/payroll-payslip'
      fullPath: '/payroll-payslip'
      preLoaderRoute: typeof PayrollPayslipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payslip': {
      id: '/payslip'
      path: '/payslip'
      fullPath: '/payslip'
      preLoaderRoute: typeof PayslipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petty-cash': {
      id: '/petty-cash'
      path: '/petty-cash'
      fullPath: '/petty-cash'
      preLoaderRoute: typeof PettyCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-images': {
      id: '/product-images'
      path: '/product-images'
      fullPath: '/product-images'
      preLoaderRoute: typeof ProductImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-scanner': {
      id: '/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/qr-scanner'
      preLoaderRoute: typeof QrScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-preview': {
      id: '/receipt-preview'
      path: '/receipt-preview'
      fullPath: '/receipt-preview'
      preLoaderRoute: typeof ReceiptPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-orders': {
      id: '/remote-orders'
      path: '/remote-orders'
      fullPath: '/remote-orders'
      preLoaderRoute: typeof RemoteOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports-generator': {
      id: '/reports-generator'
      path: '/reports-generator'
      fullPath: '/reports-generator'
      preLoaderRoute: typeof ReportsGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-dashboard': {
      id: '/staff-dashboard'
      path: '/staff-dashboard'
      fullPath: '/staff-dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-report': {
      id: '/super-report'
      path: '/super-report'
      fullPath: '/super-report'
      preLoaderRoute: typeof SuperReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-updates': {
      id: '/system-updates'
      path: '/system-updates'
      fullPath: '/system-updates'
      preLoaderRoute: typeof SystemUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/till-management': {
      id: '/till-management'
      path: '/till-management'
      fullPath: '/till-management'
      preLoaderRoute: typeof TillManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trail-balance': {
      id: '/trail-balance'
      path: '/trail-balance'
      fullPath: '/trail-balance'
      preLoaderRoute: typeof TrailBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view-business': {
      id: '/view-business'
      path: '/view-business'
      fullPath: '/view-business'
      preLoaderRoute: typeof ViewBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AddAccountRoute: AddAccountRoute,
  AddAdminRoute: AddAdminRoute,
  AddBusinessRoute: AddBusinessRoute,
  AddCashEntryRoute: AddCashEntryRoute,
  AddTransactionRoute: AddTransactionRoute,
  BalanceSheetRoute: BalanceSheetRoute,
  BranchRoute: BranchRoute,
  BranchEditRoute: BranchEditRoute,
  BranchViewRoute: BranchViewRoute,
  BranchesRoute: BranchesRoute,
  CashBookRoute: CashBookRoute,
  CreateBranchRoute: CreateBranchRoute,
  CreateUserRoute: CreateUserRoute,
  CustomerFileRoute: CustomerFileRoute,
  CustomerPortalRoute: CustomerPortalRoute,
  CustomersRoute: CustomersRoute,
  DebtorPaymentRoute: DebtorPaymentRoute,
  EditAdminRoute: EditAdminRoute,
  EditBusinessRoute: EditBusinessRoute,
  EditProductRoute: EditProductRoute,
  EmployeeRoute: EmployeeRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  ExpiryRoute: ExpiryRoute,
  IncomeStatementRoute: IncomeStatementRoute,
  InventoryRoute: InventoryRoute,
  InvoicePreviewRoute: InvoicePreviewRoute,
  LedgerRoute: LedgerRoute,
  ListBranchesRoute: ListBranchesRoute,
  LoginRoute: LoginRoute,
  ManageAdminRoute: ManageAdminRoute,
  ManageBusinessRoute: ManageBusinessRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  NotificationRoute: NotificationRoute,
  OrderNotificationsRoute: OrderNotificationsRoute,
  PaymentProofsRoute: PaymentProofsRoute,
  PayrollRoute: PayrollRoute,
  PayrollPayslipRoute: PayrollPayslipRoute,
  PayslipRoute: PayslipRoute,
  PettyCashRoute: PettyCashRoute,
  PosRoute: PosRoute,
  ProductImagesRoute: ProductImagesRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  QrScannerRoute: QrScannerRoute,
  ReceiptPreviewRoute: ReceiptPreviewRoute,
  RemoteOrdersRoute: RemoteOrdersRoute,
  ReportsRoute: ReportsRoute,
  ReportsGeneratorRoute: ReportsGeneratorRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalesRoute: SalesRoute,
  SignupRoute: SignupRoute,
  SmsRoute: SmsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  SubscriptionRoute: SubscriptionRoute,
  SuperRoute: SuperRoute,
  SuperReportRoute: SuperReportRoute,
  SuppliersRoute: SuppliersRoute,
  SystemUpdatesRoute: SystemUpdatesRoute,
  TillManagementRoute: TillManagementRoute,
  TrackOrderRoute: TrackOrderRoute,
  TrailBalanceRoute: TrailBalanceRoute,
  ViewBusinessRoute: ViewBusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
